name: "Terraform Cloud Workspace Auto Update"
description: "Update Terraform Cloud workspace terraform version based on remote config"
branding:
  icon: "chevrons-up"
  color: "purple"
inputs:
  working_dir:
    description: "Terraform work directory"
    default: "./"
  force_update:
    description: "Force to update the latest version"
    default: false
  comment_pr:
    description: "If Whether or not to comment on GitHub pull requests"
    default: false
  specific_version:
    description: "Update to the specific version"
outputs:
  result:
    description: "Check or update result message (empty if new version is not released)"
runs:
  using: "docker"
  image: "./Dockerfile"
