on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test_not_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check version
        id: check
        uses: chroju/terraform-cloud-updater@4c53f35
        with:
          tfe_token: ${{ secrets.TFE_TOKEN }}
          working_dir: ./terraform
          comment_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: result
        run: echo "${{ steps.check.outputs.output }}"
        if: "${{ steps.check.outputs.is_available_update == 'true' }}"
  test_update_and_fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check version
        id: check
        uses: chroju/terraform-cloud-updater@4c53f35
        with:
          tfe_token: ${{ secrets.TFE_TOKEN }}
          working_dir: ./terraform
          force_update: true
          comment_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: result
        run: echo "${{ steps.check.outputs.output }}"
        if: "${{ steps.check.outputs.is_available_update == 'true' }}"
