on:
  push:
  pull_request:
    branches:
      - master

env:
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_not_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check version
        id: check
        uses: chroju/terraform-cloud-updater@4b98889
        with:
          workdir: ./test
          comment_pr: true
      - name: result
        run: echo "${{ steps.check.outputs.result }}"
        if: "${{ steps.check.outputs.result != '' }}"
